mysqlMaster:
  dataSource: root:123456@tcp(10.3.138.80)/test?charset=utf8
  maxIdleConns: 1
  maxOpenConns: 1

mysqlSlaves:
  - dataSource: root:123456@tcp(10.3.138.80)/testa?charset=utf8
    maxIdleConns: 1
    maxOpenConns: 1
  - dataSource: root:123456@tcp(10.3.138.80)/testb?charset=utf8
    maxIdleConns: 1
    maxOpenConns: 1